const dummyorders = [
    {
      sellerSku: 'ABC123',
      product: 'Product A',
      period: 'Jan 2024',
      number: 1,
      status: 'Active',
      pageViews: 1000,
      itemsSold: 50,
      revenue: 5000,
    },
    {
      sellerSku: 'DEF456',
      product: 'Product B',
      period: 'Jan 2024',
      number: 2,
      status: 'Inactive',
      pageViews: 800,
      itemsSold: 30,
      revenue: 3000,
    },
    {
      sellerSku: 'GHI789',
      product: 'Product C',
      period: 'Feb 2024',
      number: 3,
      status: 'Active',
      pageViews: 1200,
      itemsSold: 70,
      revenue: 7000,
    },
    {
      sellerSku: 'JKL012',
      product: 'Product D',
      period: 'Feb 2024',
      number: 4,
      status: 'Inactive',
      pageViews: 600,
      itemsSold: 20,
      revenue: 2000,
    },
    {
        sellerSku: 'GHI789',
        product: 'Product C',
        period: 'Feb 2024',
        number: 3,
        status: 'Active',
        pageViews: 1200,
        itemsSold: 70,
        revenue: 7000,
      },
      {
        sellerSku: 'JKL012',
        product: 'Product D',
        period: 'Feb 2024',
        number: 4,
        status: 'Inactive',
        pageViews: 600,
        itemsSold: 20,
        revenue: 2000,
      },
  ];
  
  export default dummyorders;
  